apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    name: ssm-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "24h"
  target:
    name: github-repo
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - find:
        path: /environment/argocd/
        name:
          regexp: /environment/argocd/repo-(.*)
      rewrite:
        - regexp:
            source: /environment/argocd/repo-(.*)
            target: $1
