apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../../../variants/homelab-us-east-2
  - ../../../../bases/argocd/base

replacements:
  - path: environment-replacement.yaml
