apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
spec:
  secretStoreRef:
    name: ssm-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "24h"
  target:
    name: controller-manager
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - find:
        path: /environment/arc/
        name:
          regexp: /environment/arc/(.*)
      rewrite:
        - regexp:
            source: /environment/arc/(.*)
            target: $1
