---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ssm-sync
spec:
  scaleDownDelaySecondsAfterScaleOut: 3600
  scaleTargetRef:
    kind: RunnerDeployment
    name: ssm-sync
  minReplicas: 0
  maxReplicas: 2
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - ssm-sync
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ssm-sync
spec:
  template:
    spec:
      containers:
        - name: runner
          image: summerwind/actions-runner:ubuntu-20.04
      repository: larntz/ssm-sync
      labels:
        - homelab
