apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:larntz/gitops-demo.git
    path: envs/homelab/crds
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
