apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:larntz/i-see-iac.git
    path: envs/homelab/crds
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  # This solves a bug where argo-cd will mark the application as healthy but OutOfSync
  # this occurs because cert-manager updates the status field in the CRD. This field
  # makes argo-cd diff's think it is out of sync.
  # https://github.com/argoproj/argo-cd/issues/2239
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.acme.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: orders.acme.cert-manager.io
      jsonPointers:
        - /status
