apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./actions.summerwind.dev_horizontalrunnerautoscalers.yaml
  - ./actions.summerwind.dev_runnerdeployments.yaml
  - ./actions.summerwind.dev_runnerreplicasets.yaml
  - ./actions.summerwind.dev_runners.yaml
  - ./actions.summerwind.dev_runnersets.yaml
  - ./actions.github.com_autoscalinglisteners.yaml
  - ./actions.github.com_autoscalingrunnersets.yaml
  - ./actions.github.com_ephemeralrunners.yaml
  - ./actions.github.com_ephemeralrunnersets.yaml
