apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  secretStoreRef:
    name: ssm-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "24h"
  target:
    name: aws-credentials
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - find:
        path: /environment/cert-manager/
        name:
          regexp: /environment/cert-manager/(.*)
      rewrite:
        - regexp:
            source: /environment/cert-manager/(.*)
            target: $1
